"""Field model update

Revision ID: 06f9e7ed8c97
Revises: 1363dde7f160
Create Date: 2024-04-29 18:48:03.850812

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision = '06f9e7ed8c97'
down_revision = '1363dde7f160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['docfield.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('docfield', sa.Column('signer_id', sa.Integer(), nullable=True))
    op.add_column('docfield', sa.Column('optional', sa.Boolean(), nullable=True))
    op.add_column('docfield', sa.Column('checked', sa.Boolean(), nullable=True))
    op.add_column('docfield', sa.Column('mention', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('docfield', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('docfield', sa.Column('max_length', sa.Integer(), nullable=True))
    op.add_column('docfield', sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('docfield', sa.Column('instruction', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('docfield', sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'docfield', 'signatory', ['signer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'docfield', type_='foreignkey')
    op.drop_column('docfield', 'text')
    op.drop_column('docfield', 'instruction')
    op.drop_column('docfield', 'question')
    op.drop_column('docfield', 'max_length')
    op.drop_column('docfield', 'name')
    op.drop_column('docfield', 'mention')
    op.drop_column('docfield', 'checked')
    op.drop_column('docfield', 'optional')
    op.drop_column('docfield', 'signer_id')
    op.drop_table('radio')
    # ### end Alembic commands ###
