"""Replace VIEWED status with SEEN in DocumentStatus enum

Revision ID: 0be014d168b7
Revises: a50acb66db41
Create Date: 2024-05-28 15:56:06.229323

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0be014d168b7'
down_revision = 'a50acb66db41'
branch_labels = None
depends_on = None

def upgrade():
    # Update the DocumentStatus enum to replace 'VIEWED' with 'SEEN'
    op.execute("ALTER TYPE documentstatus RENAME TO documentstatus_old")
    op.execute("CREATE TYPE documentstatus AS ENUM('DRAFT', 'SENT_FOR_SIGNATURE', 'VIEWED', 'SIGNED', 'REJECTED')")
    op.execute("""
        ALTER TABLE document
        ALTER COLUMN status TYPE documentstatus USING status::text::documentstatus
    """)
    op.execute("DROP TYPE documentstatus_old")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
