"""Add default value to role field in User model

Revision ID: 0e5802466e8d
Revises: 6c2c3c03affa
Create Date: 2024-04-03 16:20:20.225236

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "0e5802466e8d"
down_revision = "6c2c3c03affa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
