"""Correct documents field name in SignatureRequest table

Revision ID: 1363dde7f160
Revises: 5bb042cf0b4c
Create Date: 2024-04-26 12:12:50.820608

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision = '1363dde7f160'
down_revision = '5bb042cf0b4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
