"""Add  field to Document model

Revision ID: 22ea936032bd
Revises: 593fd2824233
Create Date: 2024-07-01 15:13:08.377781

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision = '22ea936032bd'
down_revision = '593fd2824233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.alter_column('document', 'deleted', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'deleted')
    # ### end Alembic commands ###
