"""Fields added to DocField model

Revision ID: 34bbb6d414a0
Revises: 7cc2ee90e4b0
Create Date: 2024-06-02 22:21:34.593724

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '34bbb6d414a0'
down_revision = '7cc2ee90e4b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docfield', sa.Column('optional', sa.Boolean(), nullable=True))
    op.add_column('docfield', sa.Column('mention', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('docfield', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('docfield', sa.Column('max_length', sa.Integer(), nullable=True))
    op.add_column('docfield', sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('docfield', sa.Column('instruction', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('docfield', sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('docfield', 'text')
    op.drop_column('docfield', 'instruction')
    op.drop_column('docfield', 'question')
    op.drop_column('docfield', 'max_length')
    op.drop_column('docfield', 'name')
    op.drop_column('docfield', 'mention')
    op.drop_column('docfield', 'optional')
    # ### end Alembic commands ###
