"""Add nullable possibility to document_id field in DocField model

Revision ID: 593fd2824233
Revises: 6932873114c9
Create Date: 2024-06-27 18:29:25.490964

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision = "593fd2824233"
down_revision = "6932873114c9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "docfield", "document_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_constraint(
        "documentsignaturedetails_document_id_fkey",
        "documentsignaturedetails",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "documentsignaturedetails",
        "document",
        ["document_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "documentsignaturedetails", type_="foreignkey")
    op.create_foreign_key(
        "documentsignaturedetails_document_id_fkey",
        "documentsignaturedetails",
        "document",
        ["document_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "docfield", "document_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
