"""Add  RequestDocumentLink table

Revision ID: 5bb042cf0b4c
Revises: beaad68007f5
Create Date: 2024-04-26 11:12:49.219026

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision = '5bb042cf0b4c'
down_revision = 'beaad68007f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requestdocumentlink',
    sa.Column('signature_request_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['signature_request_id'], ['signaturerequest.id'], ),
    sa.PrimaryKeyConstraint('signature_request_id', 'document_id')
    )
    op.drop_constraint('signaturerequest_document_id_fkey', 'signaturerequest', type_='foreignkey')
    op.drop_column('signaturerequest', 'document_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signaturerequest', sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('signaturerequest_document_id_fkey', 'signaturerequest', 'document', ['document_id'], ['id'])
    op.drop_table('requestdocumentlink')
    # ### end Alembic commands ###
