"""Adding new status for Document and SignatureRequest, linking AuditLog with Signatory

Revision ID: 622d30b4f766
Revises: c47e35509720
Create Date: 2024-06-24 17:48:50.350385

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision = "622d30b4f766"
down_revision = "c47e35509720"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("auditlog", sa.Column("signatory_id", sa.Integer(), nullable=True))
    op.add_column(
        "auditlog", sa.Column("signature_request_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "documentsignaturedetails",
        sa.Column("document_id", sa.Integer(), nullable=True),
    )
    op.add_column("document", sa.Column("owner_id", sa.Integer(), nullable=True))
    op.add_column("signatory", sa.Column("creator_id", sa.Integer(), nullable=True))
    op.add_column("radio", sa.Column("field_id", sa.Integer(), nullable=True))
    op.add_column(
        "docfield", sa.Column("signature_request_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "reminder_settings", sa.Column("request_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "auditlog", "signatory", ["signatory_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "documentsignaturedetails",
        "document",
        ["document_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "document", "owner", ["owner_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "signatory", "creator", ["creator_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "radio", "doc_field", ["field_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "docfield", "signatory", ["signer_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "auditlog",
        "signature_request",
        ["signature_request_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "remindersettings", "request", ["request_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "auditlog", type_="foreignkey")
    op.drop_constraint(None, "documentsignaturedetails", type_="foreignkey")
    op.drop_constraint(None, "document", type_="foreignkey")
    op.drop_constraint(None, "signatory", type_="foreignkey")
    op.drop_constraint(None, "radio", type_="foreignkey")
    op.drop_constraint(None, "docfield", type_="foreignkey")
    op.drop_constraint(None, "remindersettings", type_="foreignkey")
    op.drop_column("auditlog", "signatory_id")
    op.drop_column("auditlog", "signature_request_id")
    op.drop_column("documentsignaturedetails", "document_id")
    op.drop_column("document", "owner_id")
    op.drop_column("signatory", "creator_id")
    op.drop_column("radio", "field_id")
    op.drop_column("docfield", "signer_id")
    op.drop_column("remindersettings", "request_id")
    # ### end Alembic commands ###
