"""Adding new status for Document and SignatureRequest, linking AuditLog with Signatory

Revision ID: 622d30b4f766
Revises: c47e35509720
Create Date: 2024-06-24 17:48:50.350385

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '622d30b4f766'
down_revision = 'c47e35509720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auditlog', sa.Column('signatory_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'auditlog', 'signatory', ['signatory_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auditlog', type_='foreignkey')
    op.drop_column('auditlog', 'signatory_id')
    # ### end Alembic commands ###
