"""Add cascade delete to Models

Revision ID: 6932873114c9
Revises: 05d2bfc3b8f9
Create Date: 2024-06-27 17:30:15.385148

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision = "6932873114c9"
down_revision = "05d2bfc3b8f9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "auditlog_signature_request_id_fkey", "auditlog", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "auditlog", "signaturerequest", ["signature_request_id"], ["id"]
    )
    op.drop_constraint("docfield_signer_id_fkey", "docfield", type_="foreignkey")
    op.create_foreign_key(None, "docfield", "signatory", ["signer_id"], ["id"])
    op.drop_constraint("document_owner_id_fkey", "document", type_="foreignkey")
    op.create_foreign_key(None, "document", "user", ["owner_id"], ["id"])
    op.drop_constraint(
        "documentsignaturedetails_document_id_fkey",
        "documentsignaturedetails",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "documentsignaturedetails", "document", ["document_id"], ["id"]
    )
    op.drop_constraint("radio_field_id_fkey", "radio", type_="foreignkey")
    op.create_foreign_key(None, "radio", "docfield", ["field_id"], ["id"])
    op.drop_constraint("signatory_creator_id_fkey", "signatory", type_="foreignkey")
    op.create_foreign_key(None, "signatory", "user", ["creator_id"], ["id"])
    op.drop_constraint(
        "signaturerequest_sender_id_fkey", "signaturerequest", type_="foreignkey"
    )
    op.create_foreign_key(None, "signaturerequest", "user", ["sender_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "signaturerequest", type_="foreignkey")
    op.create_foreign_key(
        "signaturerequest_sender_id_fkey",
        "signaturerequest",
        "user",
        ["sender_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "signatory", type_="foreignkey")
    op.create_foreign_key(
        "signatory_creator_id_fkey",
        "signatory",
        "user",
        ["creator_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "radio", type_="foreignkey")
    op.create_foreign_key(
        "radio_field_id_fkey",
        "radio",
        "docfield",
        ["field_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "documentsignaturedetails", type_="foreignkey")
    op.create_foreign_key(
        "documentsignaturedetails_document_id_fkey",
        "documentsignaturedetails",
        "document",
        ["document_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "document", type_="foreignkey")
    op.create_foreign_key(
        "document_owner_id_fkey",
        "document",
        "user",
        ["owner_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "docfield", type_="foreignkey")
    op.create_foreign_key(
        "docfield_signer_id_fkey",
        "docfield",
        "signatory",
        ["signer_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "auditlog", type_="foreignkey")
    op.create_foreign_key(
        "auditlog_signature_request_id_fkey",
        "auditlog",
        "signaturerequest",
        ["signature_request_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
