"""Make the role optional in User model

Revision ID: 72ed6056ff06
Revises: 0e5802466e8d
Create Date: 2024-04-03 16:25:47.732459

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "72ed6056ff06"
down_revision = "0e5802466e8d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "role", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "role", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
