"""checked field added to DocField model

Revision ID: 7cc2ee90e4b0
Revises: 8f293fab1560
Create Date: 2024-06-02 22:02:59.217271

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7cc2ee90e4b0'
down_revision = '8f293fab1560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docfield', sa.Column('checked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('docfield', 'checked')
    # ### end Alembic commands ###
