"""Field model update 3

Revision ID: a1892a80569c
Revises: d19d0295411a
Create Date: 2024-04-30 11:47:49.157575

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a1892a80569c'
down_revision = 'd19d0295411a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
