"""Seconde Initial migration

Revision ID: a2f1534d733b
Revises: 9b83b97311e9
Create Date: 2024-05-15 10:47:59.385522

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a2f1534d733b'
down_revision = '9b83b97311e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docfield',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('SIGNATURE', 'MENTION', 'TEXT', 'CHECKBOX', 'RADIO_GROUP', 'READ_ONLY_TEXT', name='fieldtype'), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('signature_request_id', sa.Integer(), nullable=False),
    sa.Column('signer_id', sa.Integer(), nullable=True),
    sa.Column('optional', sa.Boolean(), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=True),
    sa.Column('mention', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('instruction', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['signature_request_id'], ['signaturerequest.id'], ),
    sa.ForeignKeyConstraint(['signer_id'], ['signatory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requestdocumentlink',
    sa.Column('signature_request_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['signature_request_id'], ['signaturerequest.id'], ),
    sa.PrimaryKeyConstraint('signature_request_id', 'document_id')
    )
    op.create_table('radio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['docfield.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('radio')
    op.drop_table('requestdocumentlink')
    op.drop_table('docfield')
    # ### end Alembic commands ###
