"""Add VIEWED status to DocumentStatus enum

Revision ID: a50acb66db41
Revises: dd4accba5a67
Create Date: 2024-05-28 15:22:25.025789

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a50acb66db41'
down_revision = 'dd4accba5a67'
branch_labels = None
depends_on = None


def upgrade():
    # Update the DocumentStatus enum to include 'VIEWED'
    op.execute("ALTER TYPE documentstatus ADD VALUE 'viewed'")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
