"""Add require_otp field to SignatureRequest model

Revision ID: ab3bfbcf6428
Revises: a9ab5173f15f
Create Date: 2024-06-11 19:35:51.796573

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision = "ab3bfbcf6428"
down_revision = "a9ab5173f15f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "signaturerequest", sa.Column("require_otp", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("signaturerequest", "require_otp")
    # ### end Alembic commands ###
