"""Add Foreign Keys in User and Document models

Revision ID: adacd68d1bda
Revises: 72ed6056ff06
Create Date: 2024-04-08 13:32:26.025353

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'adacd68d1bda'
down_revision = '72ed6056ff06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
