"""Add  RequestSignatoryLink

Revision ID: b3d7b1829d3a
Revises: c9dd6791d4aa
Create Date: 2024-04-25 17:53:00.659192

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision = 'b3d7b1829d3a'
down_revision = 'c9dd6791d4aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remindersettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interval_in_days', sa.Integer(), nullable=False),
    sa.Column('max_occurrences', sa.Integer(), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requestsignatorylink',
    sa.Column('signature_request_id', sa.Integer(), nullable=False),
    sa.Column('signatory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['signatory_id'], ['signatory.id'], ),
    sa.ForeignKeyConstraint(['signature_request_id'], ['signaturerequest.id'], ),
    sa.PrimaryKeyConstraint('signature_request_id', 'signatory_id')
    )
    op.add_column('signaturerequest', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('signaturerequest', sa.Column('delivery_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint('signaturerequest_signatory_id_fkey', 'signaturerequest', type_='foreignkey')
    op.drop_column('signaturerequest', 'signatory_id')
    op.drop_column('signaturerequest', 'reminder_settings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signaturerequest', sa.Column('reminder_settings', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('signaturerequest', sa.Column('signatory_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('signaturerequest_signatory_id_fkey', 'signaturerequest', 'signatory', ['signatory_id'], ['id'])
    op.drop_column('signaturerequest', 'delivery_mode')
    op.drop_column('signaturerequest', 'name')
    op.drop_table('requestsignatorylink')
    op.drop_table('remindersettings')
    # ### end Alembic commands ###
