"""models, schemas and crud apdates

Revision ID: be65b3f0dcf2
Revises: e4f68fef267f
Create Date: 2024-04-17 09:22:02.878730

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be65b3f0dcf2'
down_revision = 'e4f68fef267f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentsignatorylink',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('signatory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['signatory_id'], ['signatory.id'], ),
    sa.PrimaryKeyConstraint('document_id', 'signatory_id')
    )
    op.alter_column('document', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'SENT_FOR_SIGNATURE', 'SIGNED', 'REJECTED', name='documentstatus'),
               nullable=True)
    op.add_column('signatory', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.add_column('signatory', sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('signatory', sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('signatory', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('signatory', 'signer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('signatory_document_id_fkey', 'signatory', type_='foreignkey')
    op.create_foreign_key(None, 'signatory', 'user', ['creator_id'], ['id'])
    op.drop_column('signatory', 'document_id')
    op.add_column('signaturerequest', sa.Column('signatory_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'signaturerequest', 'user', ['signatory_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'signaturerequest', type_='foreignkey')
    op.drop_column('signaturerequest', 'signatory_id')
    op.add_column('signatory', sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'signatory', type_='foreignkey')
    op.create_foreign_key('signatory_document_id_fkey', 'signatory', 'document', ['document_id'], ['id'])
    op.alter_column('signatory', 'signer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('signatory', 'email')
    op.drop_column('signatory', 'last_name')
    op.drop_column('signatory', 'first_name')
    op.drop_column('signatory', 'creator_id')
    op.alter_column('document', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'SENT_FOR_SIGNATURE', 'SIGNED', 'REJECTED', name='documentstatus'),
               nullable=False)
    op.drop_table('documentsignatorylink')
    # ### end Alembic commands ###
