"""ReminderSettings link to SignatureRequest correction2

Revision ID: beaad68007f5
Revises: fcc424bb69cf
Create Date: 2024-04-25 19:55:03.842153

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision = 'beaad68007f5'
down_revision = 'fcc424bb69cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('signaturerequest_reminder_settings_id_fkey', 'signaturerequest', type_='foreignkey')
    op.drop_column('signaturerequest', 'reminder_settings_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signaturerequest', sa.Column('reminder_settings_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('signaturerequest_reminder_settings_id_fkey', 'signaturerequest', 'remindersettings', ['reminder_settings_id'], ['id'])
    # ### end Alembic commands ###
