"""Add  field to 

Revision ID: c47e35509720
Revises: ab3bfbcf6428
Create Date: 2024-06-12 15:44:34.864549

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision = "c47e35509720"
down_revision = "ab3bfbcf6428"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "signaturerequest",
        sa.Column("token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("signaturerequest", "token")
    # ### end Alembic commands ###
