"""Modify the fields linking SignatureRequest to Signatory

Revision ID: c9dd6791d4aa
Revises: 841630e649fa
Create Date: 2024-04-25 12:32:41.422199

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision = 'c9dd6791d4aa'
down_revision = '841630e649fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
