"""Add VIEWED status to DocumentStatus enum

Revision ID: dd4accba5a67
Revises: a6018e78b10c
Create Date: 2024-05-28 10:14:30.145906

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dd4accba5a67'
down_revision = 'a6018e78b10c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
