"""ReminderSettings link to SignatureRequest correction

Revision ID: fcc424bb69cf
Revises: b3d7b1829d3a
Create Date: 2024-04-25 19:48:30.855822

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision = 'fcc424bb69cf'
down_revision = 'b3d7b1829d3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remindersettings', sa.Column('request_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'remindersettings', 'signaturerequest', ['request_id'], ['id'])
    op.add_column('signaturerequest', sa.Column('reminder_settings_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'signaturerequest', 'remindersettings', ['reminder_settings_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'signaturerequest', type_='foreignkey')
    op.drop_column('signaturerequest', 'reminder_settings_id')
    op.drop_constraint(None, 'remindersettings', type_='foreignkey')
    op.drop_column('remindersettings', 'request_id')
    # ### end Alembic commands ###
