"""Add deleted field to SignatureRequest model

Revision ID: ff9ab60f1f17
Revises: 22ea936032bd
Create Date: 2024-07-02 16:28:32.413388

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision = 'ff9ab60f1f17'
down_revision = '22ea936032bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signaturerequest', sa.Column('deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.alter_column('signaturerequest', 'deleted', server_default=None)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signaturerequest', 'deleted')
    # ### end Alembic commands ###
