/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as ResetPasswordImport } from './routes/reset-password';
import { Route as RecoverPasswordImport } from './routes/recover-password';
import { Route as LoginImport } from './routes/login';
import { Route as LayoutImport } from './routes/_layout';
import { Route as LayoutIndexImport } from './routes/_layout/index';
import { Route as LayoutSignaturerequestsImport } from './routes/_layout/signature_requests';
import { Route as LayoutSettingsImport } from './routes/_layout/settings';
import { Route as LayoutItemsImport } from './routes/_layout/items';
import { Route as LayoutDocumentsImport } from './routes/_layout/documents';
import { Route as LayoutCreatesignaturerequestImport } from './routes/_layout/create_signature_request';
import { Route as LayoutAdminImport } from './routes/_layout/admin';

// Create/Update Routes

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any);

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any);

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any);

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any);

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any);

const LayoutSignaturerequestsRoute = LayoutSignaturerequestsImport.update({
  path: '/signature_requests',
  getParentRoute: () => LayoutRoute,
} as any);

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any);

const LayoutItemsRoute = LayoutItemsImport.update({
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any);

const LayoutDocumentsRoute = LayoutDocumentsImport.update({
  path: '/documents',
  getParentRoute: () => LayoutRoute,
} as any);

const LayoutCreatesignaturerequestRoute =
  LayoutCreatesignaturerequestImport.update({
    path: '/new_signature_requests',
    getParentRoute: () => LayoutRoute,
  } as any);

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport;
      parentRoute: typeof rootRoute;
    };
    '/login': {
      preLoaderRoute: typeof LoginImport;
      parentRoute: typeof rootRoute;
    };
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport;
      parentRoute: typeof rootRoute;
    };
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport;
      parentRoute: typeof rootRoute;
    };
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport;
      parentRoute: typeof LayoutImport;
    };
    '/_layout/create_signature_request': {
      preLoaderRoute: typeof LayoutCreatesignaturerequestImport;
      parentRoute: typeof LayoutImport;
    };
    '/_layout/documents': {
      preLoaderRoute: typeof LayoutDocumentsImport;
      parentRoute: typeof LayoutImport;
    };
    '/_layout/items': {
      preLoaderRoute: typeof LayoutItemsImport;
      parentRoute: typeof LayoutImport;
    };
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport;
      parentRoute: typeof LayoutImport;
    };
    '/_layout/signature_requests': {
      preLoaderRoute: typeof LayoutSignaturerequestsImport;
      parentRoute: typeof LayoutImport;
    };
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport;
      parentRoute: typeof LayoutImport;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAdminRoute,
    LayoutCreatesignaturerequestRoute,
    LayoutDocumentsRoute,
    LayoutItemsRoute,
    LayoutSettingsRoute,
    LayoutSignaturerequestsRoute,
    LayoutIndexRoute,
  ]),
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
]);

/* prettier-ignore-end */
